apiVersion: v1
kind: ConfigMap
metadata:
  name: node-script
#  namespace: default
data:
  index.js: |
    var os = require('os');
    var http = require('http');
    
    http.createServer(function (req, res) {
      console.log(req.headers);
      console.log(req.method, req.url);
      
      res.setHeader('Content-Type', 'application/json');

      res.write(JSON.stringify({
          hostname: os.hostname(),
          headers: req.headers,
          method: req.method,
          url: req.url
      }));
      
      res.end(); //end the response
    }).listen(3000);

---
